### ISSUE TITLE
add sqlite

### ISSUE THREAD

**Issue by mpadge** [hrbrmstr/vershist#1]
hey @hrbrmstr this package is a rockin :guitar:  awesome idea! I'd send a PR but too lazy right now, so issue instead. I'm sure you've already thought of this obvious extension, but this would be supremely useful for internally bundled packages:
```
my_mongo <- 3.6.x
testthat::expect_identical(my_mongo, vershist::mongodb_latest())
```
And if you include `sqlite3`, then I'd use it straight away for vendor version bundled in [`bikedata`](https://github.com/ropensci/bikedata). ([And here too.](https://github.com/r-dbi/RSQLite/issues/252)) I'll PR that if I find me some :clock1130:

**Comment by hrbrmstr** [comment]
I'll bump it to the top of the list today :-)

The impetus for the pkg came from a recurring need for me to look at version distributions from scan banner grabs and to also make things like this:

![image](https://user-images.githubusercontent.com/509878/37705205-9fb9493e-2cd1-11e8-992a-2b8bd3282b16.png)

We're doing quite a bit more of this and if I don't put things in a pkg they tend to get lost in the "useful-r-things" folder :-)

**Comment by hrbrmstr** [comment]
SQLite's in there now. 

Lemme noodle on how I can optimize a "latest" function for these things. For bits like MySQL it's an expensive call but I'm also not sure how many folks want to rely on internet connectivity (i.e. if I did a daily regen of a file and sync'd it to GH so an online check could be made).
